# Welcome to abhishtagatya.github.io
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gatya | Designer and Tech Enthusiast
email: abhishtagatya@yahoo.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my website, created with Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  abhishtagatya
permalink: /404.html

port: 4000

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
